### ISSUE TITLE
how to set up a so beautiful desktop

### ISSUE THREAD

**Issue by criver31** [amnweb/dotfiles#2]
Hello, i see this link [https://github.com/LGUG2Z/komorebi?tab=readme-ov-file#demonstrations](https://github.com/LGUG2Z/komorebi?tab=readme-ov-file#demonstrations) that your desktop is so much beautiful !!! and the statusBar at the top of desktop ,so beautiful! can you tell me what components are used, as well as the configuration? ths!!!

**Comment by amnweb** [comment]
Top bar is https://github.com/amnweb/yasb I don't have this config from video but you can easy make it and style as you want.
